# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b1bf60579ee40ba802032592bf4c185ddf6976505e12f6b5383c6a08798398864c91f0b574f5a09093f0300ed95a2760854c323af1f0e42b2f3fdfc2966a7a5

test:
  secret_key_base: cb96743efefce858fd32f5500d0dda84484a48c17890cc1d8903ac1daa53adeac3d5670882183198730fe6ce415db726f93ce95891372018c67f59372e4ffd88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
